# å…·ä½“é…ç½®æ–‡æ¡£åœ°å€ https://github.com/lowlighter/metrics/blob/master/action.yml
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference

name: GitHub metrics
on:
  schedule: 
      - cron: "0 0 * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # base metrics
      - name: base_metrics
        uses: lowlighter/metrics@latest
        with:
          filename: base_metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: LikeFrost
          template: classic
          config_timezone: Asia/Shanghai
          committer_message: ":rocket: Update"
          base: "header, activity, community, repositories"
          plugin_traffic: yes
          plugin_lines: yes
      
      # plugin metrics
      - name: plugin_metrics
        uses: lowlighter/metrics@latest
        with:
          filename: plugin_metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: LikeFrost
          template: classic
          committer_message: ":rocket: Update"
          base: ""
          config_timezone: Asia/Shanghai
          
          # ğŸˆ·ï¸ Most used languages å¸¸ç”¨è¯­è¨€ç»Ÿè®¡
          plugin_languages: yes
          plugin_languages_ignored: html, css                               # List of languages to ignore (å¿½ç•¥è¯­è¨€)
          plugin_languages_skipped: LikeFrost                              # List of repositories to skip (å¿½ç•¥ä»“åº“)
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..."      # Make most used languages orange and JavaScript red (è¯­è¨€é…è‰²)
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..."     # Customize languages names with aliases (é‡å‘½åè¯­è¨€)
          plugin_languages_details: bytes-size, percentage                  # Additionally display total bytes size and percentage (æ˜¾ç¤ºå¤§å°å’Œç™¾åˆ†æ¯”)
          plugin_languages_threshold: 2%                                    # Hides all languages less than 2% (éšè—å æ¯”è¾ƒå°‘çš„è¯­è¨€)
          plugin_languages_limit: 8                                         # Display up to 8 languages (æ˜¾ç¤ºçš„è¯­è¨€ç§æ•°)
          plugin_languages_sections: most-used                              # Display most used and recently used languages stats
          plugin_languages_indepth: no                                      # Get indepth stats (see documentation before enabling) 
          plugin_languages_categories: programming                          # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming           # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500                                 # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 14                                  # Limit recently used stats to last week (æœ€è¿‘ä½¿ç”¨çš„è¯­è¨€ç»Ÿè®¡èŒƒå›´)
